### ISSUE TITLE
[QUERY] How to deploy with npm module dependencies?

### ISSUE THREAD

**Issue by oeed** [slackapi/deno-slack-hooks#89]
**Question**

I am trying to use [an npm module](https://github.com/jsarafajr/slackify-markdown) as there is no native Deno equivalent. I am trying to convert GitHub markdown to Slack's custom markdown format (if there's another way to do this please let me know!).

```ts
import slackifyMarkdown from "npm:slackify-markdown"
```

This works perfectly locally with `slack run`. However, when deploying I get a bunch of errors from `deno_esbuild` relating to resolving sub-dependencies. For example:

```
✘ [ERROR] NPM package not found. [plugin deno-loader]
    ../../../../Library/Caches/deno/deno_esbuild/remark-gfm@1.0.0/node_modules/remark-gfm/index.js:3:21:
      3 │ var syntax = require('micromark-extension-gfm')
        ╵                      ~~~~~~~~~~~~~~~~~~~~~~~~~
✘ [ERROR] NPM package not found. [plugin deno-loader]
    ../../../../Library/Caches/deno/deno_esbuild/remark-parse@9.0.0/node_modules/remark-parse/index.js:5:27:
      5 │ var fromMarkdown = require('mdast-util-from-markdown')
✘ [ERROR] Import 'https://./exists.ts' failed: error sending request for url (https://./exists.ts): error trying to connect: invalid dnsname [plugin deno-loader]
    https://deno.land/std@0.67.0/fs/move.ts:2:35:
      2 │ import { exists, existsSync } from "./exists.ts";
        ╵                                    ~~~~~~~~~~~~~
✘ [ERROR] Import 'https://../path/mod.ts' failed: error sending request for url (https://../path/mod.ts): error trying to connect: invalid dnsname [plugin deno-loader]
    https://deno.land/std@0.67.0/fs/ensure_link.ts:2:22:
      2 │ import * as path from "../path/mod.ts";
```

The strange thing is, it seems to resolve direct dependencies of `slackify-markdown` such as `remark-gfm` okay, but not their dependencies. Additionally, all the dependency files are indeed in the Deno cache folder, so I don't know why it's not resolving them. I haven't used Deno before so apologies if this is obvious!

<img width="392" alt="Screenshot 2024-07-01 at 11 18 45" src="https://github.com/slackapi/deno-slack-sdk/assets/3835991/3a2877e7-782b-4fcb-a794-de1dead58eda">

**Environment**

**The `deno-slack` versions**
deno_slack_sdk: 2.12.0
deno_slack_api: 2.4.0

**Deno runtime version**
CLI: 2.26.0
deno: 1.44.4
typescript: 5.4.5
v8: 12.6.228.9

**OS info**

macOS 14.5

**Requirements**

Please read the [Contributing guidelines](https://github.com/slackapi/deno-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by jdppettit** [comment]
Has there been any movement or work arounds for this issue? We are running into a similar problem but with `@smithy/util-utf8`:

```
⠦ Packaging app for deployment✘ [ERROR] NPM package not found. [plugin deno-loader]
    ../../Library/Caches/deno/deno_esbuild/@aws-crypto/util@5.2.0/node_modules/@aws-crypto/util/build/module/convertToBuffer.js:3:44:
      3 │ import { fromUtf8 as fromUtf8Browser } from "@smithy/util-utf8";
        ╵                                             ~~~~~~~~~~~~~~~~~~~
⠧ Packaging app for deploymentError bundling function file "lock" with esbuild
error: Uncaught (in promise) Error: Build failed with 1 error:
../../Library/Caches/deno/deno_esbuild/@aws-crypto/util@5.2.0/node_modules/@aws-crypto/util/build/module/convertToBuffer.js:3:44: ERROR: [plugin: deno-loader] NPM package not found.
  let error = new Error(text);
              ^
    at failureErrorWithLog (https://deno.land/x/esbuild@v0.19.4/mod.js:1626:15)
    at https://deno.land/x/esbuild@v0.19.4/mod.js:1035:25
    at runOnEndCallbacks (https://deno.land/x/esbuild@v0.19.4/mod.js:1461:45)
    at buildResponseToResult (https://deno.land/x/esbuild@v0.19.4/mod.js:1033:7)
    at https://deno.land/x/esbuild@v0.19.4/mod.js:1062:16
    at responseCallbacks.<computed> (https://deno.land/x/esbuild@v0.19.4/mod.js:679:9)
    at handleIncomingPacket (https://deno.land/x/esbuild@v0.19.4/mod.js:739:9)
    at readFromStdout (https://deno.land/x/esbuild@v0.19.4/mod.js:655:7)
    at https://deno.land/x/esbuild@v0.19.4/mod.js:1924:11
    at eventLoopTick (ext:core/01_core.js:175:7)
Packaging app for deployment
```

**Comment by filmaj** [comment]
Sorry, no update. We are not prioritizing this class of issues at this time. If you have feedback about this, or wish for Slack to prioritize it, please email feedback@slack.com and/or use the `/feedback` command from the Slack client.

**Comment by ThisGuyCodes** [comment]
I am running into this issue trying to use [Octokit](https://github.com/octokit/octokit.js). I tried using esm.sh instead, but this [ran](https://github.com/esm-dev/esm.sh/issues/916) [into](https://github.com/esm-dev/esm.sh/issues/918) [other](https://github.com/octokit/octokit.js/issues/2762) [issues](https://github.com/octokit/octokit.js/issues/2759).

Not being able to build Github integrations is seriously limiting my ability or desire to use this tool.

**Comment by ThisGuyCodes** [comment]
I was able to get `slack deploy` to work with native `npm:*` dependencies by adding the following to my `deno.jsonc`:
```json
  "scopes": {
    "https://deno.land/x/deno_slack_hooks@1.3.1/": {
      "https://deno.land/x/esbuild_deno_loader@0.8.2/mod.ts": "jsr:@luca/esbuild-deno-loader@0.11.0"
    }
  },
```

Looking at recent commits, it appears [a similar update](https://github.com/slackapi/deno-slack-hooks/commit/5b312237d719ae931a14c8a31647ef6373817e6b) (with more sweeping changes) has been made since the last release. Perhaps this is solved by cutting a new release?

**Comment by emilygarner** [comment]
@ThisGuyCodes Hello, I am running into a similar issue, and I have added your snippit to my "import_map.jsonc" because it would not work in my deno.jsonc. So I am able to deploy it now, but after deployment, one of my functions will not run due to a weird error : ```
Caught error from user supplied module: TypeError: Relative import path "querystring" not prefixed with / or ./ or ../
        If you want to use a built-in Node module, add a "node:" prefix (ex. "node:querystring").
```
But I am not even using this module at all in my function. Any help would be appreciated greatly. Is there something else you updated along with this snippit? Thank you.

**Comment by ThisGuyCodes** [comment]
@emilygarner in theory it should be the same in the import map, so that change seems fine.

I did not run into the problem you are having, but it's probably a sub-dependency of something you're using. Based on the full stack trace you can probably figure out what dependency that is, and add an import scope for that:

```json
"scopes": {
  "DEPENDENCY_WITH_UNPREFIXED_NODE_PACKAGE": {
    "querystring": "node:querystring"
  },
  ...
},
```

The scopes are a way of overriding dependency resolution within other packages (where as the import map affects dependency resolution of *your* package).

I don't exactly remember why, but I did also end up overriding the esbuild version, this is my full scopes section now:
```json
  "scopes": {
    "https://deno.land/x/deno_slack_hooks@1.3.1/": {
      "https://deno.land/x/esbuild_deno_loader@0.8.2/mod.ts": "jsr:@luca/esbuild-deno-loader@0.11.0",
      "https://deno.land/x/esbuild@v0.19.4/mod.js": "https://deno.land/x/esbuild@v0.24.0/mod.js"
    }
  },
```

**Comment by emilygarner** [comment]
@ThisGuyCodes Thank you for the response! I added all of that to my project but unfortunately I am still seeing the same error even after redeploying😞
